// Mocks generated by Mockito 5.4.4 from annotations
// in mvvm_project/test/features/home/data/data_source/remote/remote_data_source_home.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mvvm_project/features/features_home/data/network/api_currencyConverter.dart'
    as _i6;
import 'package:mvvm_project/features/features_home/data/network/apiHome.dart'
    as _i3;
import 'package:mvvm_project/features/features_home/data/responeses/model_country.dart'
    as _i5;
import 'package:mvvm_project/features/features_home/data/responeses/response_convert.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeResponseConvert_0 extends _i1.SmartFake
    implements _i2.ResponseConvert {
  _FakeResponseConvert_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResponsehistorical_1 extends _i1.SmartFake
    implements _i2.Responsehistorical {
  _FakeResponsehistorical_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ApiHome].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiHome extends _i1.Mock implements _i3.ApiHome {
  MockApiHome() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i5.ModelCountry>> getcountrys() => (super.noSuchMethod(
        Invocation.method(
          #getcountrys,
          [],
        ),
        returnValue:
            _i4.Future<List<_i5.ModelCountry>>.value(<_i5.ModelCountry>[]),
      ) as _i4.Future<List<_i5.ModelCountry>>);
}

/// A class which mocks [ApiCurrencyConverter].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiCurrencyConverter extends _i1.Mock
    implements _i6.ApiCurrencyConverter {
  MockApiCurrencyConverter() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.ResponseConvert> Convert(
    String? from,
    String? to,
    String? amount, {
    String? api_key = r'feb466c199-9c670905e6-sn3ff0',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #Convert,
          [
            from,
            to,
            amount,
          ],
          {#api_key: api_key},
        ),
        returnValue:
            _i4.Future<_i2.ResponseConvert>.value(_FakeResponseConvert_0(
          this,
          Invocation.method(
            #Convert,
            [
              from,
              to,
              amount,
            ],
            {#api_key: api_key},
          ),
        )),
      ) as _i4.Future<_i2.ResponseConvert>);

  @override
  _i4.Future<_i2.Responsehistorical> getHistorical(
    String? from,
    String? to,
    String? date, {
    String? api_key = r'feb466c199-9c670905e6-sn3ff0',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getHistorical,
          [
            from,
            to,
            date,
          ],
          {#api_key: api_key},
        ),
        returnValue:
            _i4.Future<_i2.Responsehistorical>.value(_FakeResponsehistorical_1(
          this,
          Invocation.method(
            #getHistorical,
            [
              from,
              to,
              date,
            ],
            {#api_key: api_key},
          ),
        )),
      ) as _i4.Future<_i2.Responsehistorical>);
}
